const PAPER_STATUS_NOT_REVIEWED = 'not reviewed';
const PAPER_STATUS_CHANGES_REQUESTED = 'changes requested';
const PAPER_STATUS_APPROVED = 'approved';

const PAPER_STATUS_DEFAULT = PAPER_STATUS_NOT_REVIEWED;

const PAPER_STATUSES = [
  PAPER_STATUS_NOT_REVIEWED,
  PAPER_STATUS_CHANGES_REQUESTED,
  PAPER_STATUS_APPROVED,
];

exports.PAPER_STATUS_NOT_REVIEWED = PAPER_STATUS_NOT_REVIEWED;
exports.PAPER_STATUS_CHANGES_REQUESTED = PAPER_STATUS_CHANGES_REQUESTED;
exports.PAPER_STATUS_APPROVED = PAPER_STATUS_APPROVED;

exports.PAPER_STATUS_DEFAULT = PAPER_STATUS_DEFAULT;

exports.PAPER_STATUSES = PAPER_STATUSES;
