const REVIEW_DECISION_APPROVED = 'approved';
const REVIEW_DECISION_CHANGES_REQUESTED = 'changes_requested';

exports.REVIEW_DECISION_APPROVED = REVIEW_DECISION_APPROVED;
exports.REVIEW_DECISION_CHANGES_REQUESTED = REVIEW_DECISION_CHANGES_REQUESTED;
