const AUTHOR_ROLE = 'author';
const ORGANIZER_ROLE = 'organizer';
const REVIEWER_ROLE = 'reviewer';

const DEFAULT_USER_ROLE = AUTHOR_ROLE;

const VALID_USER_ROLES = [AUTHOR_ROLE, ORGANIZER_ROLE, REVIEWER_ROLE];

exports.AUTHOR_ROLE = AUTHOR_ROLE;
exports.ORGANIZER_ROLE = ORGANIZER_ROLE;
exports.REVIEWER_ROLE = REVIEWER_ROLE;
exports.DEFAULT_USER_ROLE = DEFAULT_USER_ROLE;
exports.VALID_USER_ROLES = VALID_USER_ROLES;
